# Generated by §coder — 2026-04-29
class Shomea < Formula
  desc "Meeting transcription with first-class Hebrew support"
  homepage "https://github.com/asakin/shomea"
  url "https://github.com/asakin/shomea/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5"
  license "MIT"

  depends_on "ffmpeg"
  depends_on "python@3.12"

  def install
    venv = virtualenv_create(libexec, "python3.12")
    venv.pip_install(buildpath)
    bin.install_symlink libexec/"bin/shomea"
  end

  def caveats
    <<~EOS
      To download transcription models (~2GB total):
        shomea models --download

      To start the background daemon (watches ~/Documents/Zoom):
        shomea install-daemon

      Granola companion (requires Granola with Labs enabled):
        shomea granola-patch
    EOS
  end

  test do
    assert_match "shomea", shell_output("#{bin}/shomea --help")
  end
end
